import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { MereProofDapp } from '@/components/MereProofDapp'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'
import { mereProofConfig } from '@/services/utils'

export default function Home() {
  const { connectionStatus } = useWallet()

  return (
    <>
      <div className={styles.container}>
        <AlephiumConnectButton />
        <Head>
          <title>MereProof</title>
          <meta name="description" content="Generated by @alephium/cli init" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {connectionStatus === 'connected' && <MereProofDapp config={mereProofConfig} />}
      </div>
    </>
  )
}
